export const prefix = 'showcase/processes';

export const actionsIDs = {
  FETCHED_PROCESSES: `${prefix}/FETCHED_PROCESSES`,
  PROCESSES_SUBSCRIPTION: `${prefix}/PROCESSES-SUBSCRIPTION`,

  PROCESSES_SERVICE_ERROR: `${prefix}/PROCESSES_SERVICE_ERROR`,
  PROCESSES_SERVICE_ALIVE: `${prefix}/PROCESSES_SERVICE_ALIVE`,
};
